CHAMPIONS: dict[str, dict[str, int]] = {
  "Aatrox": {"Gold": 5, "Board Size": 1},
  "Ahri": {"Gold": 5, "Board Size": 1},
  "Akshan": {"Gold": 3, "Board Size": 1},
  "Aphelios": {"Gold": 4, "Board Size": 1},
  "Ashe": {"Gold": 2, "Board Size": 1},
  "Azir": {"Gold": 4, "Board Size": 1},
  "Bel'Veth": {"Gold": 5, "Board Size": 1},
  "Cassiopeia": {"Gold": 1, "Board Size": 1},
  "Cho'Gath": {"Gold": 1, "Board Size": 1},
  "Darius": {"Gold": 3, "Board Size": 1},
  "Ekko": {"Gold": 3, "Board Size": 1},
  "Galio": {"Gold": 2, "Board Size": 1},
  "Garen": {"Gold": 3, "Board Size": 1},
  "Gwen": {"Gold": 4, "Board Size": 1},
  "Heimerdinger": {"Gold": 5, "Board Size": 1},
  "Irelia": {"Gold": 1, "Board Size": 1},
  "Jarvan IV": {"Gold": 4, "Board Size": 1},
  "Jayce": {"Gold": 3, "Board Size": 1},
  "Jhin": {"Gold": 1, "Board Size": 1},
  "Jinx": {"Gold": 2, "Board Size": 1},
  "KSante": {"Gold": 5, "Board Size": 1},
  "Kaisa": {"Gold": 4, "Board Size": 1},
  "Kalista": {"Gold": 3, "Board Size": 1},
  "Karma": {"Gold": 3, "Board Size": 1},
  "Kassadin": {"Gold": 2, "Board Size": 1},
  "Katarina": {"Gold": 3, "Board Size": 1},
  "Kayle": {"Gold": 1, "Board Size": 1},
  "Kled": {"Gold": 2, "Board Size": 1},
  "Lissandra": {"Gold": 3, "Board Size": 1},
  "Lux": {"Gold": 4, "Board Size": 1},
  "Malzahar": {"Gold": 1, "Board Size": 1},
  "Maokai": {"Gold": 1, "Board Size": 1},
  "Nasus": {"Gold": 4, "Board Size": 1},
  "Orianna": {"Gold": 1, "Board Size": 1},
  "Poppy": {"Gold": 1, "Board Size": 1},
  "Rek'Sai": {"Gold": 3, "Board Size": 1},
  "Renekton": {"Gold": 1, "Board Size": 1},
  "Ryze": {"Gold": 5, "Board Size": 1},
  "Samira": {"Gold": 1, "Board Size": 1},
  "Sejuani": {"Gold": 4, "Board Size": 1},
  "Senna": {"Gold": 5, "Board Size": 1},
  "Sett": {"Gold": 2, "Board Size": 1},
  "Shen": {"Gold": 4, "Board Size": 1},
  "Sion": {"Gold": 5, "Board Size": 1},
  "Sona": {"Gold": 3, "Board Size": 1},
  "Soraka": {"Gold": 2, "Board Size": 1},
  "Swain": {"Gold": 2, "Board Size": 1},
  "Taliyah": {"Gold": 2, "Board Size": 1},
  "Taric": {"Gold": 3, "Board Size": 1},
  "Teemo": {"Gold": 2, "Board Size": 1},
  "Tristana": {"Gold": 1, "Board Size": 1},
  "Urgot": {"Gold": 4, "Board Size": 1},
  "Vel'Koz": {"Gold": 3, "Board Size": 1},
  "Vi": {"Gold": 2, "Board Size": 1},
  "Viego": {"Gold": 1, "Board Size": 1},
  "Warwick": {"Gold": 2, "Board Size": 1},
  "Yasuo": {"Gold": 4, "Board Size": 1},
  "Zed": {"Gold": 2, "Board Size": 1},
  "Zeri": {"Gold": 4, "Board Size": 1}
}

def champion_board_size(champion: str) -> int:
    """Takes a string (champion name) and returns board size of champion"""
    return CHAMPIONS[champion]["Board Size"]

def champion_gold_cost(champion: str) -> int:
    """Takes a string (champion name) and returns gold of champion"""
    return CHAMPIONS[champion]["Gold"]
